version: "3.8"

services:
  # Redis Stack
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    networks:
      - my-network

  # Zookeeper
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Use service name here instead of IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Use service name for internal communication
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_PORT: 9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
